# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniintro',
            name='image',
            field=models.FileField(upload_to='assets/images'),
        ),
    ]
