# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_auto_20180621_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
