# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_portfolio_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='project_link',
        ),
    ]
